exclude: 'node_modules|.git'
default_stages: [commit]
fail_fast: false


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        files: "hrms.*"
        exclude: ".*json$|.*txt$|.*csv|.*md"
      - id: check-yaml
      - id: no-commit-to-branch
        args: ['--branch', 'develop']
      - id: check-merge-conflict
      - id: check-ast

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-bugbear',
        ]
        args: ['--config', '.github/helper/.flake8_strict']
        exclude: ".*setup.py$"

  - repo: https://github.com/adityahase/black
    rev: 9cb0a69f4d0030cdf687eddf314468b39ed54119
    hooks:
      - id: black
        additional_dependencies: ['click==8.0.4']

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [javascript, css, scss]
        # Ignore any files that might contain jinja / bundles
        exclude: |
            (?x)^(
                hrms/public/dist/.*|
                .*node_modules.*|
                .*boilerplate.*|
                hrms/templates/includes/.*|
                hrms/hr/doctype/employee_promotion/employee_promotion.js|
                hrms/hr/doctype/employee_transfer/employee_transfer.js|
            )$

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: ".*setup.py$"

ci:
    autoupdate_schedule: weekly
    skip: []
    submodules: false